import React from "react"
import ASE from "../assets/ass-enc.png"
import CCoin from "../assets/crypto-coin.jpeg"
import MMask from "../assets/metamask.png"
import SE from "../assets/Symetric-Key-Encryption.jpeg"
import Accordion from '@mui/material/Accordion';
import AccordionSummary from '@mui/material/AccordionSummary';
import AccordionDetails from '@mui/material/AccordionDetails';
import Typography from '@mui/material/Typography';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import SE1 from "../assets/img_1.png"

const Home = () => {
    console.log('Home is => ')
    return(
        <>
        <div>
        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            aria-controls="panel1a-content"
            id="panel1a-header"
          >
            <Typography><h1>About Crypto-Currency</h1></Typography>
          </AccordionSummary>
          <Typography>
              <div style = {{textAlign: "center"}}>
                  <img src = {CCoin} width = "50%" height = "200px"  />
              </div>
              <div>
              A cryptocurrency (or “crypto”) is a form of payment that can circulate without the need for a central monetary authority such as a government or bank. Instead, cryptocurrencies are created using cryptographic techniques that enable people to buy, sell or trade them securely.

Cryptocurrencies can be exchanged for goods and services, though they often are used as investment vehicles. Cryptocurrency is also a key part of the operation of some decentralized financial networks, where digital tokens are an important tool for carrying out transactions.

The most popular cryptocurrency, Bitcoin, has had a historically volatile price. In 2021, it hit an all-time high above $65,000 before falling back.
More than 16,000 different cryptocurrencies are traded publicly.
              </div>
          </Typography>
          <AccordionDetails>
          </AccordionDetails>
          
        </Accordion>
        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            aria-controls="panel2a-content"
            id="panel2a-header"
          >
             <Typography>
                <h1>About Symmetric Encryption </h1>
            </Typography>
          </AccordionSummary>
          <Typography>
          <div style = {{textAlign: "center"}}>
            <img src = {SE} width = "50%" height = "200px" />
            </div>
          </Typography>
          <AccordionDetails>
            <Typography>
            <div>
              Symmetric encryption is a means of protecting data using a secret key to encrypt (lock) and decrypt (unlock) it. The sender and recipient share the key or password to gain access to the information. 
              The key can be a word; a phrase; or a nonsensical or random string of letters, numbers, and symbols.
              Symmetric encryption uses algorithms to convert data into a form that can only be understood by those who have access to the secret key. The key can be a code or random string of letters, numbers, and symbols generated by a random number generator (RNG). 
              Some of the symmetric algorithms available are:
              <ul>
                  <li>Data Encryption Standard: Data Encryption Standard (DES) used to be the standardized method for encrypting various modes of electronic communications but was soon phased out. 
                      It was found weak and insufficient to address the higher processing power requirements of most modern computers.
                      </li>
                      <li>Advanced Encryption Standard: One of the most popular symmetric encryption algorithms still in use to date is the Advanced Encryption Standard (AES). The NIST set this algorithm as the standard for encrypting electronic data. The AES cipher contains a block size of 128 bits 
                          but may include different key lengths (AES-128, AES-192, and AES-256).</li>
                    <li>
                    International Data Encryption Algorithm: The International Data Encryption Algorithm (IDEA) is widely used to secure big data separated into chunks.
                    </li>
              </ul>
              Other symmetric encryption algorithms include Blowfish, Rivest Cipher 4 (RC4), Rivest Cipher 5 (RC5), and Rivest Cipher 6 (RC6).
              </div>
              <div>
                  <h3>How Does Symmetric Encryption Work?</h3>
                  <p>Symmetric encryption works the same way as locking the door to a family’s home to which only the husband and the wife hold the key. Even when neighbors or their in-laws try to open the door, they can’t do so unless they use any of the couple’s keys. When other people take the key from the husband or wife, they can open the door even without the knowledge or presence of the couple.

In symmetric encryption, the key that encrypts a message or file is the same key that can decrypt them. The sender of the data uses the symmetric key algorithm to encrypt the original data and turn it into cipher text. The encrypted message is then sent to the receiver who uses the same symmetric key to decrypt or open the cipher text or turn it back into readable form.</p>
<div style = {{textAlign: "center"}}>
    <img src = {SE1} width = "50%" height = "150px" />
</div>
If somebody other than the intended recipient gets access to the symmetric key, he/she can also decrypt the message. For this reason, symmetric encryption is considered less secure compared to asymmetric encryption. Needless to say, careful and secure handling of the key is necessary to protect data and its owners.
              </div>
              <div>
                  <h3>What Is Symmetric Encryption Used for?</h3>
                  <p>Despite being an older form of securing data, symmetric encryption is still widely used because it is easy to deploy compared to asymmetric encryption (i.e., using a pair of related keys to encrypt and decrypt data). With better performance, symmetric cryptography is used for securing tons of data, such as that contained in databases.

Symmetric encryption also plays an important role in website security, specifically on how Hypertext Transfer Protocol Secure (HTTPS) works. While asymmetric encryption is used at the initial stage of an HTTPS connection, the rest of the data transfer is handled using symmetric encryption, as it is faster.</p>
              </div>
              <div>
                  <h3>What Are the Drawbacks of Symmetric Encryption?</h3>
                  <ul>
                      <li>
                      Prone to Key Leakage : Symmetric encryption is easy to hack because once a portion of the key is leaked, hackers can easily reconstruct the entire key and gain access to confidential data.
                      </li>
                      <li>
                      Lack of Attribution Data: Another downside of using symmetric encryption is its lack of embedded metadata or attribution data. It does not allow users to record information in an access control list nor let them monitor usage based on expiration dates
                      </li>
                      <li>
                      Absence of Management System: Key management is essential when using symmetric encryption. When the keys in use remain few, manual monitoring is possible. However, when used on a large scale, manually tracking secret keys can be impractical, which can become problematic, particularly for transactions that contain tons of sensitive information, such as millions of EMV card payments.
                      </li>
                  </ul>
              </div>
            </Typography>
          </AccordionDetails>
        </Accordion>

        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            aria-controls="panel3a-content"
            id="panel3a-header"
          >
            <Typography>
                <h1>About Asymmetric Encryption</h1>
            </Typography>
          </AccordionSummary>
          <Typography>
                <div style = {{textAlign: "center"}}>
                    <img src = {ASE} width = "50%" height = "200px" />
                </div>
            </Typography>
            <AccordionDetails>
                <Typography>
                As government officials explain, non-sensitive web traffic just doesn't exist. We share almost every part of our lives online, and we conduct extremely sensitive transactions every day. Both individuals and companies need robust security measures in an environment like this. Asymmetric encryption is made to help. 

Security in an asymmetric encryption environment comes from two keys.
<ul>
    <li>Public key encryption: Anyone can see this and access it. </li>
    <li>Private key encryption: Only the authenticated recipient has access to it. </li>
</ul>
These two keys are separate but equal, and they're both required to decode a message. If you have only one, decryption is impossible. 

Symmetric encryption is asymmetric encryption's counterpart. If you use symmetric encryption, one key both encrypts and decrypts data. A hacker with access to that one key can do both functions. 

Asymmetric encryption relies on two keys. One encrypts, and the other decodes. The result is a stronger level of security.
<div>
    <h3>How Does Asymmetric Cryptography Work?</h3>
    <p>Sensitive messages move through a process of encryption and decryption with public and private keys. 

An algorithm starts the process. A mathematical function generates a key pair. Each key is different, but they are related to one another mathematically. 

Key generation protocols differ, and the keys they create are different too. In the Microsoft environment, for example, you need about four lines of code to start the development of a pair of asymmetric keys. Other programs work in a similar manner. 

Imagine that someone wants to send an encrypted message to another person. The process looks like this:
<ul>
    <li>Registration: The user and the sender have connected with an official entity that generated both public and private keys.</li>
    <li>Lookup: The sender scours a public-key directory for the recipient's public key information. </li>
    <li>Encrypt: The sender creates a message, encrypts it with the recipient's public key, and sends it. </li>
    <li>Decode: The recipient uses the private key to unscramble the message. </li>
    <li>Reply: If the recipient wants to respond, the process moves in reverse. </li>
</ul>
Now, imagine that someone wants to communicate with an entity, not an individual. Certificates become important. 

SSL certificates, commonly used by websites, work a bit like handshakes. An organization jumps through a hoop, such as registering with an entity and proving ownership, and a certificate is created. When a user accesses a site like this, the user's computer and the website verify private and public keys before information is passed. But once verification happens, the data passes through symmetric encryption, allowing for speed. 

Web authentication is relatively easy to understand. We've all used it. But plenty of other entities use the technique to keep their users safe. Bitcoin, for example, leans heavily on asymmetric encryption. A transaction is associated with a public key, but a private key is required for a person to move that transaction from one account to another.
</p>
</div>
<div>
    <h3>Pros & Cons of Asymmetric Encryption </h3>
    <p>
        <h4>Pros</h4>
        <ul>
            <li>Security: Without both keys, a hacker can only access useless data. </li>
            <li>Transparency: Public keys can be openly distributed, as losing them will not devolve into a security risk. </li>
            <li>Appearance: Weary consumers demand robust security. Zoom discovered this in 2020, for example, when reporters uncovered lapses in code that meant Zoom calls weren't truly encrypted end to end, as mentioned in their marketing materials. Delivering a truly secure environment is critical to many people. </li>
        </ul>
        <h4>Cons</h4>
        <ul>
            <li>Speed: Systems need time for decryption. Users sending plenty of bulk files will have a long wait</li>
            <li>Vulnerabilities: Lose a private key, and anyone who finds it can read all messages, even if they're private. A lost key can result in a man-in-the-middle attack too. </li>
            <li>Loss: If you lose your private key, you won't be able to decrypt messages sent to you.</li>
            <li>Long-term sustainability: In the future, quantum computing will break most asymmetric and symmetric approaches.</li>
        </ul>
    </p>
</div>
<div>
    <h3>History of Asymmetric Encryption </h3>
    <p>The idea of protecting data isn't new. In fact, the concepts that lie beneath asymmetric cryptography were defined decades ago.

In 1977, two researchers at Stanford University published a paper with asymmetric encryption concepts clearly defined. They felt the new protocols were required, as consumers were moving from cash-only transactions to digital versions, and they needed ways to protect their finances.

In time, the ideas spread, and soon, individuals, public companies, and private endeavors all scrambled to implement this high level of security. In 1995, asymmetric encryption moved to the mainstream, as the HTTPS protocol was released for widespread use. Now, companies as large as Google use the technique to protect their communications. </p>
</div>
                </Typography>
            </AccordionDetails>
        </Accordion>
        
        <Accordion>
            <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            aria-controls="panel3a-content"
            id="panel3a-header">
                <Typography><h1>About Metamask</h1></Typography>
            </AccordionSummary>
            <Typography>
                <div style = {{textAlign: "center"}}>
                    <img src = {MMask} width = "50%" height = "300px" />
                </div>
            </Typography>
            <AccordionDetails>
                <Typography>
                MetaMask is a software cryptocurrency wallet used to interact with the Ethereum blockchain. It allows users to access their Ethereum wallet through a browser extension or mobile app, 
                which can then be used to interact with decentralized applications.
                </Typography>
            </AccordionDetails>
        </Accordion>
      </div>
        </>
    )
}

export default Home